import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect } from "react";
import styles from "../../styles/Home.module.css";
import OpenPageComponent from "../components/OpenPageComponent";
import { ProductAdded } from "../interfaces/Product";
import { baseService } from "../services/api";

type HomeProps = {
  product: { releases: ProductAdded[]; popular: ProductAdded[] };
};
export default function Home({ product }: HomeProps) {
  useEffect(() => {}, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <OpenPageComponent product={product} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer">
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { data: product } = await baseService.get<{
    releases: ProductAdded[];
    popular: ProductAdded[];
  }>("product-homepage");
  return {
    props: { product }, // will be passed to the page component as props
  };
};
